#!/usr/bin/env bash
set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAILED=0

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  FAILED=1
}

pass() {
  printf 'PASS: %s\n' "$1"
}

require_file() {
  local file="$1"
  if [ -f "$ROOT_DIR/$file" ]; then
    pass "file exists: $file"
  else
    fail "missing file: $file"
  fi
}

require_exec() {
  local file="$1"
  if [ -x "$ROOT_DIR/$file" ]; then
    pass "executable: $file"
  else
    fail "not executable: $file"
  fi
}

require_text() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  if grep -Eq -- "$pattern" "$ROOT_DIR/$file"; then
    pass "$label"
  else
    fail "$label"
  fi
}

forbid_text() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  if grep -Eq -- "$pattern" "$ROOT_DIR/$file"; then
    fail "$label"
  else
    pass "$label"
  fi
}

require_same_assignment() {
  local file_a="$1"
  local file_b="$2"
  local name="$3"
  local label="$4"
  local value_a
  local value_b
  value_a="$(sed -n "s/^${name}=//p" "$ROOT_DIR/$file_a")"
  value_b="$(sed -n "s/^${name}=//p" "$ROOT_DIR/$file_b")"
  if [ -n "$value_a" ] && [ "$value_a" = "$value_b" ]; then
    pass "$label"
  else
    fail "$label"
  fi
}

require_file "AGENTS.md"
require_file "CLAUDE.md"
require_file ".github/workflows/agentparty-release.yml"
require_file ".claude/skills/triparty/SKILL.md"
require_file ".claude/commands/triparty.md"
require_file ".claude/commands/tp.md"
require_file ".claude/commands/agentparty-claw.md"
require_file ".claude/commands/ap-claw.md"
require_file "README.md"
require_file "VERSION"
require_file "CHANGELOG.md"
require_file "docs/framework/tri-party-protocol.md"
require_file "docs/framework/agentparty-protocol.md"
require_file "docs/framework/agentparty-pack.schema.json"
require_file "docs/framework/agentparty-pack-state.schema.json"
require_file "docs/framework/agentparty-packs.json"
require_file "docs/framework/product-packs/triparty.md"
require_file "docs/framework/product-packs/claude-code-feishu-claw.md"
require_file "docs/framework/agentparty-managed-install-lifecycle.md"
require_file "docs/framework/adapter-contract.md"
require_file "docs/framework/model-binding.yaml"
require_file "docs/framework/model-binding.schema.json"
require_file "docs/framework/state.schema.json"
require_file "docs/framework/productization-strategy.md"
require_file "docs/framework/gemini-headless-policy.toml"
require_file "adapters/http/triparty_http_adapter.py"
require_file "adapters/mcp/triparty_mcp_adapter.py"
require_file "scripts/triparty-validate-state.py"
require_file "scripts/agentparty-pack-lint.py"
require_file "scripts/agentparty.py"
require_file "scripts/agentparty.sh"
require_file "scripts/agentparty.ps1"
require_file "scripts/triparty-runs-dir.sh"
require_file "scripts/triparty-gemini-auth-doctor.sh"
require_file "scripts/triparty-continuity-checkpoint.sh"
require_file "scripts/triparty-continuity-bootstrap.sh"
require_file "scripts/uninstall-triparty-global-bootstrap.sh"
require_file "scripts/uninstall-triparty-global-bootstrap.ps1"

require_exec "scripts/triparty-preflight.sh"
require_exec "scripts/triparty-review.sh"
require_exec "scripts/triparty-cross-audit.sh"
require_exec "scripts/triparty-merge.sh"
require_exec "scripts/triparty.sh"
require_exec "scripts/triparty-lint.sh"
require_exec "scripts/triparty-regression.sh"
require_exec "scripts/triparty-adapter-smoke.sh"
require_exec "scripts/triparty-mcp-smoke.sh"
require_exec "scripts/triparty-release-gate.sh"
require_exec "scripts/triparty-runs-dir.sh"
require_exec "scripts/triparty-gemini-auth-doctor.sh"
require_exec "scripts/triparty-continuity-checkpoint.sh"
require_exec "scripts/triparty-continuity-bootstrap.sh"
require_exec "scripts/install-triparty-git-hooks.sh"
require_exec "scripts/install-triparty-global-bootstrap.sh"
require_exec "scripts/uninstall-triparty-global-bootstrap.sh"
require_exec "scripts/uninstall-triparty-global-bootstrap.ps1"
require_exec "scripts/triparty-validate-state.py"
require_exec "scripts/agentparty-pack-lint.py"
require_exec "scripts/agentparty.py"
require_exec "scripts/agentparty.sh"
require_exec "adapters/http/triparty_http_adapter.py"
require_exec "adapters/mcp/triparty_mcp_adapter.py"

if bash -n "$ROOT_DIR"/scripts/*.sh; then
  pass "all shell scripts parse"
else
  fail "one or more shell scripts do not parse"
fi

if python3 "$ROOT_DIR/scripts/agentparty-pack-lint.py"; then
  pass "AgentParty product pack registry validates"
else
  fail "AgentParty product pack registry validates"
fi

require_text "AGENTS.md" 'Tri-party Mutual Audit Gate' "AGENTS records mutual audit gate"
require_text "AGENTS.md" 'Codex, Claude, and Gemini' "AGENTS names the three parties"
require_text "AGENTS.md" 'Tri-party Trigger Contract' "AGENTS records trigger contract"
require_text "AGENTS.md" 'New-session Bootstrap Contract' "AGENTS records new-session bootstrap contract"
require_text "AGENTS.md" 'Codex.*Claude.*Gemini.*三方模型协作框架' "AGENTS records canonical trigger phrase"
require_text "AGENTS.md" '/triparty' "AGENTS records slash trigger"
require_text "AGENTS.md" '/tp' "AGENTS records slash alias"
require_text "AGENTS.md" 'follow-up instructions.*inherit the tri-party protocol' "AGENTS records inherited follow-up trigger"
require_text "CLAUDE.md" '@AGENTS.md' "CLAUDE imports AGENTS"
require_text "CLAUDE.md" 'Claude Code' "CLAUDE documents Claude Code entrypoint"
require_text "CLAUDE.md" '/triparty' "CLAUDE documents slash trigger"
require_text ".claude/skills/triparty/SKILL.md" 'description:.*Codex \+ Claude \+ Gemini' "Claude skill describes canonical framework"
require_text ".claude/skills/triparty/SKILL.md" '/triparty' "Claude skill records slash trigger"
require_text ".claude/skills/triparty/SKILL.md" 'Do not recreate' "Claude skill forbids framework recreation"
require_text ".claude/skills/triparty/SKILL.md" 'Adapter Boundaries' "Claude skill records adapter boundaries"
require_text ".claude/skills/triparty/SKILL.md" 'state validation' "Claude skill records state validation"
require_text ".claude/commands/triparty.md" 'description:' "Claude triparty slash command has description"
require_text ".claude/commands/triparty.md" 'Do not recreate' "Claude triparty slash command forbids framework recreation"
require_text ".claude/commands/triparty.md" 'state validation' "Claude triparty slash command records state validation"
require_text ".claude/commands/tp.md" '/triparty' "Claude tp slash alias points to triparty"
require_text ".claude/commands/agentparty-claw.md" 'AGENTPARTY_MANAGED_COMMAND: agentparty-claw' "Claw slash command has managed marker"
require_text ".claude/commands/agentparty-claw.md" 'If all three resolution paths fail, stop' "Claw slash command hard-stops when AgentParty is undiscoverable"
require_text ".claude/commands/agentparty-claw.md" 'AGENTPARTY_CMD=.*command -v agentparty' "Claw slash command resolves AgentParty CLI before dispatch"
require_text ".claude/commands/agentparty-claw.md" 'exit 1' "Claw slash command resolver exits non-zero when undiscoverable"
require_text ".claude/commands/agentparty-claw.md" 'Do not create replacement protocol files' "Claw slash command forbids ad hoc fallback files"
require_text ".claude/commands/agentparty-claw.md" 'must not call Feishu, configure Claw auth, import evidence, or claim `pack_ready` by itself' "Claw slash command locks external side-effect boundary"
require_text ".claude/commands/agentparty-claw.md" 'Do not set or claim `true_triparty_ready=true`' "Claw slash command forbids true tri-party overclaim"
require_text ".claude/commands/agentparty-claw.md" 'does not participate in Codex \+ Claude \+ Gemini cross-audit' "Claw slash command separates 2-agent pack from tri-party cross-audit"
require_text ".claude/commands/ap-claw.md" 'AGENTPARTY_MANAGED_COMMAND: ap-claw' "Claw slash alias has managed marker"
require_text ".claude/commands/ap-claw.md" 'If no AgentParty CLI path can be resolved, stop' "Claw slash alias hard-stops when AgentParty is undiscoverable"
require_text ".claude/commands/ap-claw.md" 'AGENTPARTY_CMD=.*command -v agentparty' "Claw slash alias resolves AgentParty CLI before dispatch"
require_text ".claude/commands/ap-claw.md" 'exit 1' "Claw slash alias resolver exits non-zero when undiscoverable"
require_text ".claude/commands/ap-claw.md" 'kit.*prompt.*guide.*validate|validate.*guide.*prompt.*kit' "Claw slash alias names supported dispatch surface"
require_text ".claude/commands/ap-claw.md" 'Do not recreate the framework with new ad hoc Markdown files' "Claw slash alias forbids ad hoc fallback files"
require_text ".claude/commands/ap-claw.md" 'Do not call Feishu, configure Claw auth, import evidence, claim `pack_ready` by itself' "Claw slash alias locks external side-effect boundary"
require_text ".claude/commands/ap-claw.md" 'claim `true_triparty_ready=true`' "Claw slash alias forbids true tri-party overclaim"
forbid_text ".claude/skills/triparty/SKILL.md" 'scripts/triparty-(preflight|review|cross-audit|merge)\.sh' "Claude skill does not bypass unified CLI with stage scripts"
forbid_text ".claude/commands/triparty.md" 'scripts/triparty-(preflight|review|cross-audit|merge)\.sh' "Claude slash command does not bypass unified CLI with stage scripts"
forbid_text ".claude/commands/tp.md" 'scripts/triparty-(preflight|review|cross-audit|merge)\.sh' "Claude slash alias does not bypass unified CLI with stage scripts"
forbid_text ".claude/skills/triparty/SKILL.md" '(^|[[:space:]`])(claude|gemini)[[:space:]]+(-|--|run|chat|api)' "Claude skill does not directly invoke model CLIs"
forbid_text ".claude/commands/triparty.md" '(^|[[:space:]`])(claude|gemini)[[:space:]]+(-|--|run|chat|api)' "Claude slash command does not directly invoke model CLIs"
forbid_text ".claude/commands/tp.md" '(^|[[:space:]`])(claude|gemini)[[:space:]]+(-|--|run|chat|api)' "Claude slash alias does not directly invoke model CLIs"
require_text "README.md" 'triparty-cross-audit\.sh' "README documents cross-audit step"
require_text "README.md" 'triparty\.sh' "README documents unified CLI"
require_text "README.md" 'triparty_http_adapter\.py' "README documents HTTP adapter"
require_text "README.md" 'triparty_mcp_adapter\.py' "README documents MCP adapter"
require_text "README.md" 'triparty-release-gate\.sh' "README documents release gate"
require_text "README.md" 'Standalone phrases such as `三方框架`' "README documents weak trigger ambiguity"
require_text "README.md" 'follow-up requests.*inherit the tri-party protocol' "README documents inherited workstream trigger"
require_text "README.md" 'install-triparty-global-bootstrap\.sh' "README documents global bootstrap installer"
require_text "README.md" 'uninstall-triparty-global-bootstrap\.sh' "README documents global bootstrap uninstaller"
require_text "README.md" 'Claude Code reads `CLAUDE.md`' "README documents Claude Code bootstrap"
require_text "README.md" '/triparty status' "README documents slash trigger"
require_text "README.md" '/tp status' "README documents slash alias"
require_text "README.md" 'install-plan --pack triparty' "README documents AgentParty install-plan"
require_text "docs/framework/adapter-contract.md" 'true_triparty_ready' "adapter contract preserves core truth"
require_text "docs/framework/adapter-contract.md" 'triparty_resume' "adapter contract documents resume"
require_text "docs/framework/adapter-contract.md" 'completion_marker' "adapter contract documents artifact completion markers"
require_text "docs/framework/adapter-contract.md" 'temp-file-and-rename' "adapter contract documents atomic status publication"
require_text "docs/framework/adapter-contract.md" 'install-plan --pack <pack-id>' "adapter contract documents install-plan boundary router"
require_text "docs/framework/tri-party-protocol.md" 'Mutual Cross-audit Gate' "protocol documents mutual cross-audit gate"
require_text "docs/framework/agentparty-protocol.md" 'Skill Portability Contract' "AgentParty protocol documents skill portability contract"
require_text "docs/framework/agentparty-protocol.md" 'Completion Semantics' "AgentParty protocol documents completion semantics"
require_text "docs/framework/agentparty-protocol.md" 'Operating System Policy' "AgentParty protocol documents OS policy"
require_text "docs/framework/agentparty-packs.json" '"id": "triparty"' "AgentParty registry includes triparty pack"
require_text "docs/framework/agentparty-packs.json" '"id": "claude-code-feishu-claw"' "AgentParty registry includes Claude Code + Feishu Claw pack"
require_text "docs/framework/agentparty-pack-state.schema.json" 'agentparty\.pack-state\.v1' "AgentParty pack state schema exists"
require_text "docs/framework/product-packs/claude-code-feishu-claw.md" 'must never claim `true_triparty_ready`' "ClawCode pack forbids true tri-party claim"
require_text "docs/framework/tri-party-protocol.md" 'Claude audits Gemini' "protocol records Claude auditing Gemini"
require_text "docs/framework/tri-party-protocol.md" 'Gemini audits Claude' "protocol records Gemini auditing Claude"
require_text "docs/framework/tri-party-protocol.md" 'Activation And Ambiguity Rules' "protocol documents activation ambiguity rules"
require_text "docs/framework/tri-party-protocol.md" 'Inherited Workstream Rule' "protocol documents inherited workstream rule"
require_text "docs/framework/tri-party-protocol.md" 'New-session Discovery' "protocol documents new-session discovery"
require_text "docs/framework/tri-party-protocol.md" 'Claude Code reads `CLAUDE.md`' "protocol documents Claude Code discovery"
require_text "docs/framework/tri-party-protocol.md" 'Slash Invocation' "protocol documents slash invocation"
require_text "docs/framework/tri-party-protocol.md" '/triparty' "protocol records slash trigger"
require_text "docs/framework/tri-party-protocol.md" '/tp' "protocol records slash alias"
require_text "docs/framework/tri-party-protocol.md" 'Gemini CLI Reliability Rules' "protocol documents Gemini CLI reliability rules"
require_text "docs/framework/tri-party-protocol.md" 'release-gate' "protocol documents release gate"
require_text "docs/framework/anti-patterns.md" 'Ambiguous Tri-party Trigger Drift' "anti-patterns document trigger drift"
require_text "docs/framework/anti-patterns.md" 'Tri-party Context Drop On Follow-up Execution' "anti-patterns document context drop failure"
require_text "docs/framework/anti-patterns.md" 'Gemini Runtime Noise Counted As Clean Completion' "anti-patterns document Gemini runtime noise"
require_text "docs/framework/anti-patterns.md" 'New Session Recreates The Framework' "anti-patterns document new-session reconstruction failure"
require_text "docs/framework/anti-patterns.md" 'Slash Trigger Exists Only In Prose' "anti-patterns document slash trigger failure"
require_text "docs/framework/anti-patterns.md" 'Adapter Purity Text Misread As Source-status Contamination' "anti-patterns document adapter purity false positive"
require_text "docs/framework/anti-patterns.md" 'Release Gate Selects An Incomplete Latest Run' "anti-patterns document release-gate latest-run failure"
require_text "docs/framework/model-binding.yaml" 'required_for_true_tri_party: true' "model binding requires cross-audit"
require_text "docs/framework/model-binding.yaml" 'cli_model_name: gemini-3\.1-pro-preview' "model binding pins Gemini CLI model"
require_text "docs/framework/model-binding.yaml" '--allowed-mcp-server-names' "model binding records Gemini MCP allowlist"
require_text "docs/framework/model-binding.yaml" '__none__' "model binding disables default Gemini MCP servers"
require_text "docs/framework/model-binding.yaml" 'gemini-headless-policy\.toml' "model binding records Gemini headless policy"
require_text "docs/framework/model-binding.yaml" 'runtime_noise_is_merge_blocking: true' "model binding records runtime noise gate"
require_text "docs/framework/model-binding.yaml" 'auth_doctor_statuses' "model binding records Gemini auth doctor"
require_text "docs/framework/model-binding.yaml" 'runs_dir_fallback' "model binding records runs dir fallback"
require_text "docs/framework/model-binding.yaml" 'release_max_capacity_events: 3' "model binding records Gemini capacity threshold"
require_text "docs/framework/productization-strategy.md" 'portable core kit with thin adapters' "product strategy avoids Codex-only core"
require_text "docs/framework/productization-strategy.md" 'First External Adapter' "product strategy documents first adapter"
require_text "docs/framework/productization-strategy.md" 'MCP adapter' "product strategy documents MCP adapter"
require_text "docs/framework/productization-strategy.md" 'windows_powershell.*blocked commands|blocked commands.*windows_powershell' "product strategy documents native Windows blocked commands"
require_text "docs/framework/productization-strategy.md" 'Regression-only Windows simulation' "product strategy labels forced native Windows hook as regression-only"
require_text "docs/framework/productization-strategy.md" 'AGENTPARTY_FORCE_NATIVE_WINDOWS=1' "product strategy names forced native Windows regression hook"
require_text "docs/framework/productization-strategy.md" 'agentparty-managed-install-lifecycle\.md' "product strategy links managed install lifecycle evidence"
require_text "docs/framework/productization-strategy.md" 'separate real Windows host run' "product strategy prevents PowerShell static evidence overclaim"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'agentparty\.managed-install\.v1' "managed install lifecycle documents manifest schema"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'STATE=present' "managed install lifecycle documents present state"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'STATE=absent' "managed install lifecycle documents absent state"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'Manifest/key missing' "managed install lifecycle documents compatibility fallback"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'CLAUDE_AGENTPARTY_CLAW_COMMAND' "managed install lifecycle documents Claw command key"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'global_uninstall_respects_absent_manifest_state' "managed install lifecycle records absent-state regression"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'global_uninstall_modified_user_file_preserved' "managed install lifecycle records modified-file regression"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'global_uninstall_resumes_after_interrupted_cleanup' "managed install lifecycle records interrupted-cleanup regression"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'does not invoke `sudo`' "managed install lifecycle documents user-space install boundary"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'Capability Matrix' "managed install lifecycle documents capability matrix"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" '\[UNVERIFIED\] static/package-boundary only' "managed install lifecycle marks PowerShell scaffold unverified"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'NFS/SMB/shared filesystems' "managed install lifecycle marks shared filesystems unverified"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'unknown/empty filesystem types' "managed install lifecycle blocks unknown filesystem types"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'E_UNVERIFIED_FS' "managed install lifecycle documents unverified filesystem guard"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'content SHA-256, never on timestamps' "managed install lifecycle documents hash-based preservation"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'agentparty-managed-install-locks' "managed install lifecycle documents concurrency lock"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'atomic `mkdir`' "managed install lifecycle documents atomic lock creation"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'full target `TRIPARTY_CONFIG_DIR` hash' "managed install lifecycle documents full-path lock hash"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'normalize the[[:space:]]+lock root trailing slash|normalize.*trailing slash' "managed install lifecycle documents lock root normalization"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'owner\.env' "managed install lifecycle documents lock owner metadata"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'LOCK_OWNER_ID' "managed install lifecycle documents lock owner transaction id"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'flush/fsync' "managed install lifecycle documents owner metadata flush"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'PROCESS_STARTED_AT' "managed install lifecycle documents process start metadata"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'PROCESS_IDENTITY' "managed install lifecycle documents process identity metadata"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'BOOT_ID' "managed install lifecycle documents boot metadata"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'conservative stale-lock[[:space:]]+recovery|stale-lock[[:space:]]+recovery' "managed install lifecycle documents stale-lock recovery"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'live PID[[:space:]]+always remains fail-safe `E_LOCKED`' "managed install lifecycle blocks PID reuse auto-recovery"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'same-filesystem reclaim path' "managed install lifecycle documents atomic stale-lock reclaim"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'owner fingerprint' "managed install lifecycle documents reclaim owner fingerprint check"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'stale lock[[:space:]]+reclaim race' "managed install lifecycle documents reclaim race fail-safe"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'symlinked config paths' "managed install lifecycle documents symlink path normalization"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'E_LOCKED' "managed install lifecycle documents lock error"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'PowerShell cleanup commands' "managed install lifecycle documents explicit stale-lock cleanup commands"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'local user-space locking contract' "managed install lifecycle limits lock claims to local user-space"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'MSYS.*MINGW.*CYGWIN|CYGWIN.*MINGW.*MSYS' "managed install lifecycle documents native Windows POSIX shell block"
require_text "docs/framework/agentparty-managed-install-lifecycle.md" 'does not claim native PowerShell execution' "managed install lifecycle preserves Windows boundary"
forbid_text "README.md" 'AGENTPARTY_FORCE_NATIVE_WINDOWS' "README does not expose regression-only Windows hook"
forbid_text "web/README.md" 'AGENTPARTY_FORCE_NATIVE_WINDOWS' "website README does not expose regression-only Windows hook"
forbid_text "web/index.html" 'AGENTPARTY_FORCE_NATIVE_WINDOWS' "website does not expose regression-only Windows hook"
forbid_text "docs/framework/product-packs/claude-code-feishu-claw.md" 'AGENTPARTY_FORCE_NATIVE_WINDOWS' "Claw product-pack user doc does not expose regression-only Windows hook"
require_text "web/index.html" 'AgentParty 是底层框架' "website states AgentParty as foundation"
require_text "web/index.html" 'TriParty.*Claude Code \+ Feishu Claw|Claude Code \+ Feishu Claw.*TriParty' "website shows both product packs"
require_text "web/index.html" 'install-plan' "website exposes install-plan command"
require_text "web/README.md" 'install-plan' "website README documents install-plan"
require_text "docs/framework/state.schema.json" 'triparty.state.v1' "state schema documents state.json"
require_text "docs/framework/state.schema.json" 'preflight_binary_sha256' "state schema requires preflight binary evidence"
require_text "docs/framework/state.schema.json" 'preflight_policy_sha256' "state schema requires Gemini policy evidence"
require_text "docs/framework/state.schema.json" 'auth_doctor' "state schema documents Gemini auth doctor"
require_text "docs/framework/state.schema.json" 'gemini_diagnostics' "state schema requires Gemini diagnostics"
require_text "scripts/triparty-runs-dir.sh" 'triparty-runs' "runs-dir helper records temp fallback"
require_text "scripts/triparty-gemini-auth-doctor.sh" 'interactive-auth-required' "Gemini auth doctor reports interactive auth"
require_text "scripts/triparty-merge.sh" 'artifact_metadata_status' "merge gate validates artifact metadata"
require_text "scripts/triparty-merge.sh" 'TRIPARTY_REVIEW_COMPLETE' "merge gate validates review completion marker"
require_text "scripts/triparty-merge.sh" 'artifact_runtime_noise_status' "merge gate validates runtime noise"
require_text "scripts/triparty-merge.sh" 'Warning: True color' "merge gate treats terminal warnings as runtime noise"
require_text "scripts/triparty-preflight.sh" 'MODEL_BINDING_SHA256' "preflight records model binding hash"
require_text "scripts/triparty-preflight.sh" 'GEMINI_POLICY_SHA256' "preflight records Gemini policy hash"
require_text "scripts/triparty-preflight.sh" 'GEMINI_AUTH_STATUS' "preflight records Gemini auth status"
require_text "scripts/triparty-review.sh" 'gemini-sanitize-v2' "review records sanitizer version"
require_text "scripts/triparty.sh" 'state.json.tmp' "unified status writes state atomically"
require_text "scripts/triparty.sh" '"runs_dir"' "unified status records actual runs dir"
require_text "scripts/triparty.sh" 'release-gate' "unified CLI exposes release gate"
require_text "scripts/triparty.sh" 'continuity' "unified CLI exposes continuity handoff"
require_text "scripts/triparty.sh" 'triparty-validate-state.py' "unified run validates release state"
require_text "scripts/triparty-release-gate.sh" 'triparty-validate-state.py' "release gate validates state schema"
require_text "scripts/triparty-release-gate.sh" 'source-status\.md' "release gate filters latest run candidates by source status"
require_text "scripts/triparty-validate-state.py" 'TRIPARTY_RELEASE_MAX_GEMINI_CAPACITY_EVENTS' "state validator enforces Gemini capacity threshold"
require_text "scripts/triparty-validate-state.py" 'auth_doctor.status must be authenticated' "state validator requires Gemini auth for release"
require_text "scripts/triparty-continuity-checkpoint.sh" 'triparty-continuity/v1' "continuity checkpoint writes current.yml schema"
require_text "scripts/triparty-continuity-checkpoint.sh" 'manifest.json' "continuity checkpoint writes manifest"
require_text "scripts/triparty-continuity-bootstrap.sh" 'Hash mismatch' "continuity bootstrap verifies hashes"
require_text "scripts/install-triparty-global-bootstrap.sh" '\.triparty-framework' "global bootstrap writes discovery config"
require_text "scripts/install-triparty-global-bootstrap.sh" 'AGENTPARTY_PACK_REGISTRY' "global bootstrap writes AgentParty registry config"
require_text "scripts/install-triparty-global-bootstrap.sh" 'AgentParty CLI wrapper' "global bootstrap installs AgentParty CLI wrapper"
require_text "scripts/install-triparty-global-bootstrap.sh" 'managed-install\.env' "global bootstrap writes managed install manifest"
require_text "scripts/install-triparty-global-bootstrap.sh" 'agentparty-managed-install-locks' "global bootstrap uses managed install lock"
require_text "scripts/install-triparty-global-bootstrap.sh" 'MANAGED_INSTALL_LOCK_ROOT=.*normalize_lock_path' "global bootstrap normalizes lock root trailing slash"
require_text "scripts/install-triparty-global-bootstrap.sh" 'normalize_lock_path' "global bootstrap has reusable lock path normalization"
require_text "scripts/install-triparty-global-bootstrap.sh" 'mkdir "\$MANAGED_INSTALL_LOCK_DIR"' "global bootstrap lock creation is atomic mkdir"
require_text "scripts/install-triparty-global-bootstrap.sh" 'chmod 700 "\$MANAGED_INSTALL_LOCK_ROOT"' "global bootstrap locks user-scoped root permissions"
require_text "scripts/install-triparty-global-bootstrap.sh" 'block_unverified_lock_filesystem' "global bootstrap blocks unverified shared lock filesystems"
require_text "scripts/install-triparty-global-bootstrap.sh" 'is_verified_local_lock_filesystem' "global bootstrap fail-closes unknown lock filesystems"
require_text "scripts/install-triparty-global-bootstrap.sh" 'LOCK_FILESYSTEM_CANDIDATES' "global bootstrap centralizes lock filesystem candidates"
require_text "scripts/install-triparty-global-bootstrap.sh" 'cannot verify filesystem type' "global bootstrap reports unknown lock filesystem"
require_text "scripts/install-triparty-global-bootstrap.sh" 'LC_ALL' "global bootstrap filesystem detection fixes locale"
require_text "scripts/install-triparty-global-bootstrap.sh" 'timeout=min\(5\.0, remaining\)' "global bootstrap filesystem detection has bounded fallback"
require_text "scripts/install-triparty-global-bootstrap.sh" 'deadline = time\.monotonic\(\) \+ 15\.0' "global bootstrap filesystem detection has total fallback budget"
require_text "scripts/install-triparty-global-bootstrap.sh" 'sys\.exit\(0\)' "global bootstrap filesystem detection stops after candidate match"
require_text "scripts/install-triparty-global-bootstrap.sh" 'E_UNVERIFIED_FS' "global bootstrap emits unverified filesystem error"
require_text "scripts/install-triparty-global-bootstrap.sh" 'owner\.env' "global bootstrap writes lock owner metadata"
require_text "scripts/install-triparty-global-bootstrap.sh" 'LOCK_OWNER_ID' "global bootstrap writes lock owner transaction id"
require_text "scripts/install-triparty-global-bootstrap.sh" 'fsync_lock_metadata' "global bootstrap flushes lock owner metadata"
require_text "scripts/install-triparty-global-bootstrap.sh" 'PROCESS_STARTED_AT' "global bootstrap writes process start metadata"
require_text "scripts/install-triparty-global-bootstrap.sh" 'PROCESS_IDENTITY' "global bootstrap writes process identity metadata"
require_text "scripts/install-triparty-global-bootstrap.sh" 'BOOT_ID' "global bootstrap writes boot metadata"
require_text "scripts/install-triparty-global-bootstrap.sh" 'stale_lock_recoverable' "global bootstrap can identify stale locks"
require_text "scripts/install-triparty-global-bootstrap.sh" 'same_known_host' "global bootstrap refuses unknown or foreign host locks"
require_text "scripts/install-triparty-global-bootstrap.sh" 'lock_owner_value "LOCK_SOURCE"' "global bootstrap reads lock source before recovery"
require_text "scripts/install-triparty-global-bootstrap.sh" '"\$owner_source" != "\$MANAGED_INSTALL_LOCK_SOURCE"' "global bootstrap validates lock source before recovery"
require_text "scripts/install-triparty-global-bootstrap.sh" 'mv "\$MANAGED_INSTALL_LOCK_DIR" "\$reclaim_dir"' "global bootstrap reclaims stale locks by atomic rename"
require_text "scripts/install-triparty-global-bootstrap.sh" 'lock_owner_fingerprint_from_dir' "global bootstrap verifies reclaimed lock owner fingerprint"
require_text "scripts/install-triparty-global-bootstrap.sh" 'stale lock reclaim race detected' "global bootstrap reports reclaim race fail-safe"
require_text "scripts/install-triparty-global-bootstrap.sh" 'Lock owner pid=' "global bootstrap prints lock owner diagnostics"
require_text "scripts/install-triparty-global-bootstrap.sh" 'Recover stale AgentParty managed install lock' "global bootstrap reports stale lock recovery"
require_text "scripts/install-triparty-global-bootstrap.sh" 'rm -rf %q' "global bootstrap prints exact stale-lock cleanup command"
require_text "scripts/install-triparty-global-bootstrap.sh" 'E_LOCKED' "global bootstrap reports lifecycle lock"
require_text "scripts/install-triparty-global-bootstrap.sh" 'MINGW.*MSYS.*CYGWIN|CYGWIN.*MSYS.*MINGW' "global bootstrap blocks native Windows POSIX shells"
require_text "scripts/install-triparty-global-bootstrap.sh" 'STATE=present' "global bootstrap manifest records present state"
require_text "scripts/install-triparty-global-bootstrap.sh" 'STATE=absent' "global bootstrap manifest records absent state"
require_text "scripts/install-triparty-global-bootstrap.sh" 'write_manifest_entry "CLAUDE_AGENTPARTY_CLAW_COMMAND"' "global bootstrap records Claw command installed hash"
require_text "scripts/install-triparty-global-bootstrap.sh" 'write_manifest_entry "CLAUDE_AP_CLAW_COMMAND"' "global bootstrap records Claw alias installed hash"
require_text "scripts/install-triparty-global-bootstrap.sh" '\.claude.*/CLAUDE\.md|CLAUDE_MEMORY_FILE' "global bootstrap writes Claude Code memory"
require_text "scripts/install-triparty-global-bootstrap.sh" 'skills/triparty' "global bootstrap installs Claude slash skill"
require_text "scripts/install-triparty-global-bootstrap.sh" 'commands/tp\.md' "global bootstrap installs Claude slash alias"
require_text "scripts/install-triparty-global-bootstrap.sh" 'commands/agentparty-claw\.md' "global bootstrap installs Claude Claw slash command"
require_text "scripts/install-triparty-global-bootstrap.sh" 'commands/ap-claw\.md' "global bootstrap installs Claude Claw slash alias"
require_text "scripts/agentparty-pack-lint.py" 'non-triparty packs cannot use true_triparty_ready as ready_label' "AgentParty lint blocks non-triparty true_triparty ready label"
require_text "scripts/agentparty-pack-lint.py" 'agentparty pack-state true_triparty_ready must be const false' "AgentParty lint enforces pack-state false true_triparty field"
require_text "scripts/agentparty-pack-lint.py" 'agents must be exactly codex, claude, and gemini' "AgentParty lint pins triparty agent identity"
require_text "scripts/agentparty.py" 'Windows non-WSL AgentParty' "AgentParty core blocks native Windows executable overclaim"
require_text "scripts/agentparty.py" 'msys.*mingw.*cygwin|cygwin.*mingw.*msys' "AgentParty core blocks Windows non-WSL POSIX shells"
require_text "scripts/agentparty.py" 'def command_evidence' "AgentParty CLI imports product-pack evidence"
require_text "scripts/agentparty.py" 'def command_validate_run' "AgentParty CLI validates product-pack run state"
require_text "scripts/agentparty.py" 'info\.add_argument\("--pack"' "AgentParty info accepts --pack alias"
require_text "scripts/agentparty.py" 'E_PACK_CONFLICT' "AgentParty info rejects conflicting pack selectors"
require_text "scripts/agentparty.py" 'def command_quickstart' "AgentParty CLI prints one-copy pack quickstart"
require_text "scripts/agentparty.py" 'def command_kit' "AgentParty CLI creates Claw product kit"
require_text "scripts/agentparty.py" 'def command_bridge_kit' "AgentParty CLI creates Claw bridge kit"
require_text "scripts/agentparty.py" 'def command_bridge_validate' "AgentParty CLI validates Claw bridge state"
require_text "scripts/agentparty.py" 'START_HERE\.md' "AgentParty Claw kit writes start-here guide"
require_text "scripts/agentparty.py" 'def command_guide' "AgentParty CLI prints pack next-step guide"
require_text "scripts/agentparty.py" 'def enforce_pack_write_boundaries' "AgentParty CLI hard-blocks non-triparty true-triparty writes"
require_text "scripts/agentparty.py" 'E_BLOCKED_OS' "AgentParty CLI emits explicit blocked OS code"
require_text "scripts/agentparty.py" 'E_PACK_SCHEMA_UNKNOWN' "AgentParty CLI rejects unknown pack-state schema writes"
require_text "scripts/agentparty.py" 'def command_install' "AgentParty CLI installs managed product-pack bootstrap"
require_text "scripts/agentparty.py" 'No changes made\. Re-run with --execute' "AgentParty install defaults to dry-run"
require_text "scripts/agentparty.py" 'target_matches_host' "AgentParty install execute requires detected target match"
require_text "scripts/agentparty.py" 'Windows non-WSL AgentParty install execute is roadmap' "AgentParty install blocks native Windows execute overclaim"
require_text "scripts/agentparty.py" 'def command_install_plan' "AgentParty CLI prints OS-specific install plans"
require_text "scripts/agentparty.py" 'def command_release_check' "AgentParty CLI exposes release-check gate"
require_text "scripts/agentparty.py" 'def command_package' "AgentParty CLI exposes release package generator"
require_text "scripts/agentparty.py" 'agentparty\.package\.v1' "AgentParty package manifest schema exists"
require_text "scripts/agentparty.py" '\.claude/commands/agentparty-claw\.md' "AgentParty package includes Claw slash command"
require_text "scripts/agentparty.py" '\.claude/commands/ap-claw\.md' "AgentParty package includes Claw slash alias"
require_text "scripts/agentparty.py" 'def check_release_workflow_static' "AgentParty release-check validates release workflow"
require_text "README.md" 'quickstart --pack triparty' "README documents AgentParty quickstart"
require_text "README.md" 'info --pack claude-code-feishu-claw' "README documents AgentParty info pack alias"
require_text "README.md" '/agentparty-claw' "README documents Claw slash command"
require_text "README.md" 'kit --pack claude-code-feishu-claw' "README documents Claw kit"
require_text "README.md" 'bridge-kit --pack claude-code-feishu-claw' "README documents Claw bridge kit"
require_text "docs/framework/product-packs/claude-code-feishu-claw.md" 'bridge-validate --bridge-dir' "Claw product-pack doc documents bridge validation"
require_text "README.md" 'START_HERE\.md' "README documents Claw kit start-here guide"
require_text "README.md" 'guide --pack claude-code-feishu-claw' "README documents AgentParty guide"
require_text "README.md" 'release-check --full' "README documents AgentParty release-check"
require_text "README.md" 'package --out dist/agentparty-release --archive' "README documents AgentParty package"
require_text "web/index.html" 'quickstart --pack triparty' "website exposes AgentParty quickstart command"
require_text "web/index.html" 'info --pack claude-code-feishu-claw' "website exposes AgentParty info pack command"
require_text "web/index.html" 'kit --pack claude-code-feishu-claw' "website exposes Claw kit command"
require_text "web/index.html" '/agentparty-claw' "website documents Claw slash command"
require_text "web/index.html" 'guide --pack claude-code-feishu-claw' "website exposes AgentParty guide command"
require_text "web/index.html" 'release-check --full' "website exposes AgentParty release-check command"
require_text "web/index.html" 'package --out dist/agentparty-release --archive' "website exposes AgentParty package command"
require_text ".github/workflows/agentparty-release.yml" 'ubuntu-latest' "release workflow runs Linux package path"
require_text ".github/workflows/agentparty-release.yml" 'macos-latest' "release workflow runs macOS package path"
require_text ".github/workflows/agentparty-release.yml" 'windows-latest' "release workflow runs Windows boundary job"
require_text ".github/workflows/agentparty-release.yml" 'concurrency:' "release workflow has concurrency guard"
require_text ".github/workflows/agentparty-release.yml" 'scripts/agentparty\.sh release-check --full --json' "release workflow runs AgentParty full gate"
require_text ".github/workflows/agentparty-release.yml" 'scripts/agentparty\.sh package --out dist/agentparty-release-\$\{\{ matrix\.os \}\} --archive --force --json' "release workflow builds release bundle artifacts"
require_text ".github/workflows/agentparty-release.yml" 'actions/upload-artifact@v4' "release workflow uploads release artifacts"
require_text ".github/workflows/agentparty-release.yml" 'release-gate-summary:' "release workflow has aggregate summary job"
require_text ".github/workflows/agentparty-release.yml" 'needs\.release-check\.result' "release workflow aggregate checks release-check job"
require_text ".github/workflows/agentparty-release.yml" 'needs\.windows-boundary\.result' "release workflow aggregate checks Windows boundary job"
require_text ".github/workflows/agentparty-release.yml" 'E_BLOCKED_OS' "release workflow checks native Windows blocked commands"
require_text ".github/workflows/agentparty-release.yml" 'wsl --install -d Ubuntu' "release workflow keeps Windows WSL2 handoff"
forbid_text ".github/workflows/agentparty-release.yml" 'scripts/triparty\.sh run|triparty run' "release workflow must not execute model runs"
if python3 - "$ROOT_DIR" <<'PY'
import importlib.util
import pathlib
import sys
from html.parser import HTMLParser

root = pathlib.Path(sys.argv[1])
spec = importlib.util.spec_from_file_location("agentparty_lint_contract", root / "scripts/agentparty.py")
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)


class CommandCardParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.command_cards = 0
        self.command_card_depth = 0
        self.copy_commands = []

    def handle_starttag(self, tag, attrs):
        attr = {key: value or "" for key, value in attrs}
        starts_card = tag == "article" and "command-card" in attr.get("class", "").split()
        if starts_card:
            self.command_cards += 1
            self.command_card_depth = 1
        elif self.command_card_depth:
            self.command_card_depth += 1
        if tag == "button" and self.command_card_depth and attr.get("data-copy"):
            self.copy_commands.append(attr["data-copy"])

    def handle_endtag(self, tag):
        if self.command_card_depth:
            self.command_card_depth -= 1


parser = CommandCardParser()
parser.feed((root / "web/index.html").read_text(encoding="utf-8"))
errors = []
if parser.command_cards != module.EXPECTED_WEB_COMMAND_CARDS:
    errors.append(f"expected {module.EXPECTED_WEB_COMMAND_CARDS} command cards, found {parser.command_cards}")
if parser.copy_commands != module.EXPECTED_WEB_COPY_COMMANDS:
    missing = [command for command in module.EXPECTED_WEB_COPY_COMMANDS if command not in parser.copy_commands]
    unexpected = [command for command in parser.copy_commands if command not in module.EXPECTED_WEB_COPY_COMMANDS]
    if missing:
        errors.append("missing command cards: " + " | ".join(missing))
    if unexpected:
        errors.append("unexpected command cards: " + " | ".join(unexpected))
    if not missing and not unexpected:
        errors.append("command cards match as a set but are out of order")
if errors:
    for error in errors:
        print(error, file=sys.stderr)
    raise SystemExit(1)
PY
then
  pass "website command-card copy commands match AgentParty release-check contract"
else
  fail "website command-card copy commands match AgentParty release-check contract"
fi
require_text "scripts/agentparty.py" 'uninstall-triparty-global-bootstrap\.sh --dry-run' "AgentParty install-plan exposes cleanup dry-run"
require_text "scripts/agentparty.py" 'AGENTPARTY_RUNS_DIR' "AgentParty CLI supports testable runs dir override"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" '--execute' "Uninstaller requires explicit execute mode"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'Skip modified' "Uninstaller skips modified managed files"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'param\(' "PowerShell uninstaller has parameters"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" '\[UNVERIFIED\]' "PowerShell uninstaller warns it is unverified native scaffold"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" '-Execute' "PowerShell uninstaller requires explicit execute mode"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Skip modified' "PowerShell uninstaller skips modified managed files"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'does not enable native PowerShell run/evidence execution' "PowerShell uninstaller avoids native execution overclaim"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'agentparty-claw\.md' "Uninstaller removes managed Claw slash command"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'agentparty-claw\.md' "PowerShell uninstaller removes managed Claw slash command"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'remove_claude_command_if_managed' "Uninstaller removes historical managed Claw slash commands"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'managed_manifest_value' "Uninstaller checks managed install manifest hashes"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'agentparty-managed-install-locks' "Uninstaller uses managed install lock"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'MANAGED_INSTALL_LOCK_ROOT=.*normalize_lock_path' "Uninstaller normalizes lock root trailing slash"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'normalize_lock_path' "Uninstaller has reusable lock path normalization"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'mkdir "\$MANAGED_INSTALL_LOCK_DIR"' "Uninstaller lock creation is atomic mkdir"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'chmod 700 "\$MANAGED_INSTALL_LOCK_ROOT"' "Uninstaller locks user-scoped root permissions"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'block_unverified_lock_filesystem' "Uninstaller blocks unverified shared lock filesystems"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'is_verified_local_lock_filesystem' "Uninstaller fail-closes unknown lock filesystems"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'LOCK_FILESYSTEM_CANDIDATES' "Uninstaller centralizes lock filesystem candidates"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'cannot verify filesystem type' "Uninstaller reports unknown lock filesystem"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'LC_ALL' "Uninstaller filesystem detection fixes locale"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'timeout=min\(5\.0, remaining\)' "Uninstaller filesystem detection has bounded fallback"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'deadline = time\.monotonic\(\) \+ 15\.0' "Uninstaller filesystem detection has total fallback budget"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'sys\.exit\(0\)' "Uninstaller filesystem detection stops after candidate match"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'E_UNVERIFIED_FS' "Uninstaller emits unverified filesystem error"
require_same_assignment "scripts/install-triparty-global-bootstrap.sh" "scripts/uninstall-triparty-global-bootstrap.sh" "LOCK_FILESYSTEM_UNVERIFIED" "Installer and uninstaller share unverified filesystem list"
require_same_assignment "scripts/install-triparty-global-bootstrap.sh" "scripts/uninstall-triparty-global-bootstrap.sh" "LOCK_FILESYSTEM_VERIFIED_LOCAL" "Installer and uninstaller share verified local filesystem list"
require_same_assignment "scripts/install-triparty-global-bootstrap.sh" "scripts/uninstall-triparty-global-bootstrap.sh" "LOCK_FILESYSTEM_CANDIDATES" "Installer and uninstaller share filesystem candidate list"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'owner\.env' "Uninstaller writes lock owner metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'LOCK_OWNER_ID' "Uninstaller writes lock owner transaction id"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'fsync_lock_metadata' "Uninstaller flushes lock owner metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'PROCESS_STARTED_AT' "Uninstaller writes process start metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'PROCESS_IDENTITY' "Uninstaller writes process identity metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'BOOT_ID' "Uninstaller writes boot metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'stale_lock_recoverable' "Uninstaller can identify stale locks"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'same_known_host' "Uninstaller refuses unknown or foreign host locks"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'lock_owner_value "LOCK_SOURCE"' "Uninstaller reads lock source before recovery"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" '"\$owner_source" != "\$MANAGED_INSTALL_LOCK_SOURCE"' "Uninstaller validates lock source before recovery"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'mv "\$MANAGED_INSTALL_LOCK_DIR" "\$reclaim_dir"' "Uninstaller reclaims stale locks by atomic rename"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'lock_owner_fingerprint_from_dir' "Uninstaller verifies reclaimed lock owner fingerprint"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'stale lock reclaim race detected' "Uninstaller reports reclaim race fail-safe"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'Lock owner pid=' "Uninstaller prints lock owner diagnostics"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'Recover stale AgentParty managed install lock' "Uninstaller reports stale lock recovery"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'rm -rf %q' "Uninstaller prints exact stale-lock cleanup command"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'E_LOCKED' "Uninstaller reports lifecycle lock"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'MINGW.*MSYS.*CYGWIN|CYGWIN.*MSYS.*MINGW' "Uninstaller blocks native Windows POSIX shells"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'install manifest records it absent' "Uninstaller skips manifest-absent files"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'manifest-matched' "Uninstaller reports manifest-matched cleanup"
require_text "scripts/uninstall-triparty-global-bootstrap.sh" 'AGENTPARTY_MANAGED_COMMAND: agentparty-claw' "Uninstaller recognizes Claw slash managed marker"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Remove-ManagedClaudeCommand' "PowerShell uninstaller removes historical managed Claw slash commands"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Get-ManagedManifestValue' "PowerShell uninstaller checks managed install manifest hashes"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'agentparty-managed-install-locks' "PowerShell uninstaller uses managed install lock"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Block-UnverifiedLockFilesystem' "PowerShell uninstaller blocks unverified lock filesystems"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'E_UNVERIFIED_FS' "PowerShell uninstaller emits unverified filesystem error"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'TrimEnd' "PowerShell uninstaller normalizes lock root trailing slash"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Normalize-AgentPartyLockPath' "PowerShell uninstaller has reusable lock path normalization"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'New-Item -ItemType Directory -Path \$ManagedInstallLockDir' "PowerShell uninstaller lock creation is atomic directory create"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'owner\.env' "PowerShell uninstaller writes lock owner metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'LOCK_OWNER_ID' "PowerShell uninstaller writes lock owner transaction id"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Sync-ManagedLockMetadata' "PowerShell uninstaller flushes lock owner metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'PROCESS_STARTED_AT' "PowerShell uninstaller writes process start metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'PROCESS_IDENTITY' "PowerShell uninstaller writes process identity metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'BOOT_ID' "PowerShell uninstaller writes boot metadata"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Test-StaleManagedInstallLock' "PowerShell uninstaller can identify stale locks"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Test-AgentPartySameKnownHost' "PowerShell uninstaller refuses unknown or foreign host locks"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'OwnerLockSource.*ConfigLockSource|ConfigLockSource.*OwnerLockSource' "PowerShell uninstaller validates lock source before recovery"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Move-Item -LiteralPath \$ManagedInstallLockDir -Destination \$RecoveryDir' "PowerShell uninstaller reclaims stale locks by rename"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Get-ManagedLockOwnerFingerprint' "PowerShell uninstaller verifies reclaimed lock owner fingerprint"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'stale lock reclaim race detected' "PowerShell uninstaller reports reclaim race fail-safe"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Lock owner pid=' "PowerShell uninstaller prints lock owner diagnostics"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Recover stale AgentParty managed install lock' "PowerShell uninstaller reports stale lock recovery"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'Remove-Item -Recurse -Force -LiteralPath' "PowerShell uninstaller prints exact stale-lock cleanup command"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'E_LOCKED' "PowerShell uninstaller reports lifecycle lock"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'install manifest records it absent' "PowerShell uninstaller skips manifest-absent files"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'manifest-matched' "PowerShell uninstaller reports manifest-matched cleanup"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'AGENTPARTY_MANAGED_COMMAND: agentparty-claw' "PowerShell uninstaller recognizes Claw slash managed marker"
require_text "scripts/uninstall-triparty-global-bootstrap.ps1" 'AGENTPARTY_MANAGED_COMMAND: ap-claw' "PowerShell uninstaller recognizes Claw slash alias managed marker"
forbid_text "scripts/install-triparty-global-bootstrap.sh" '(^|[[:space:]])sudo([[:space:]]|$)' "global bootstrap installer does not use sudo"
forbid_text "scripts/uninstall-triparty-global-bootstrap.sh" '(^|[[:space:]])sudo([[:space:]]|$)' "global bootstrap uninstaller does not use sudo"
require_text "scripts/agentparty.ps1" 'PowerShell native AgentParty run is roadmap' "PowerShell wrapper blocks native run overclaim"
require_text "scripts/agentparty.ps1" 'PowerShell native AgentParty install execute is roadmap' "PowerShell wrapper blocks native install execute overclaim"
require_text "scripts/agentparty.ps1" 'PowerShell native AgentParty evidence import is roadmap' "PowerShell wrapper blocks native evidence overclaim"
require_text "scripts/agentparty.ps1" '\$KnownCommands' "PowerShell wrapper detects known subcommands"
require_text "scripts/agentparty.ps1" 'foreach \(\$Arg in \$AgentPartyArgs\)' "PowerShell wrapper scans arguments for blocked subcommands"
require_text "scripts/agentparty.ps1" 'exit 1' "PowerShell wrapper exits when Python is missing"
require_text "scripts/agentparty.ps1" 'E_BLOCKED_OS' "PowerShell wrapper emits explicit blocked OS code"
require_text "scripts/agentparty.ps1" 'wsl --install -d Ubuntu' "PowerShell wrapper points blocked users to WSL2"
require_text "README.md" 'separate Windows evidence run|Windows 真机 run' "README prevents PowerShell static evidence overclaim"
require_text "web/README.md" 'Windows 真机 run' "website README prevents PowerShell static evidence overclaim"
require_text "scripts/triparty-regression.sh" 'agentparty_triparty_install_plan_blocks_native_windows_run' "Regression covers native Windows install-plan blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_quickstart_triparty_supported_path' "Regression covers AgentParty quickstart supported path"
require_text "scripts/triparty-regression.sh" 'agentparty_quickstart_triparty_windows_native_handoff' "Regression covers AgentParty quickstart native Windows handoff"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_quickstart_auto_handoff' "Regression covers forced native Windows quickstart handoff"
require_text "scripts/triparty-regression.sh" 'agentparty_install_execute_installs_managed_bootstrap' "Regression covers AgentParty install execute"
require_text "scripts/triparty-regression.sh" 'agentparty_install_blocks_windows_native_execute' "Regression covers native Windows install execute blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_blocks_run' "Regression covers forced native Windows run blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_blocks_claw_e2e' "Regression covers forced native Windows claw-e2e blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_blocks_deep_doctor' "Regression covers forced native Windows deep doctor blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_blocks_evidence_import' "Regression covers forced native Windows evidence blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_allows_evidence_template_prep' "Regression covers forced native Windows evidence-template prep"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_fill_updates_bundle' "Regression covers Claw evidence-fill bundle updates"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_allows_evidence_fill_prep' "Regression covers native Windows evidence-fill preparation"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_kit_creates_portable_bundle' "Regression covers Claw kit generation"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_allows_claw_kit_prep' "Regression covers native Windows Claw kit preparation"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_bridge_kit_creates_shared_state' "Regression covers Claw bridge kit generation"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_bridge_validate_passes' "Regression covers Claw bridge validation"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_allows_bridge_kit_prep' "Regression covers native Windows bridge kit preparation"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_kit_bundle_marks_pack_ready' "Regression covers Claw kit bundle ready state"
require_text "scripts/triparty-regression.sh" 'agentparty_force_native_windows_allows_guide_prep' "Regression covers forced native Windows guide prep"
require_text "scripts/triparty-regression.sh" 'claw_slash_resolver_static_nonzero_boundary' "Regression covers Claw slash resolver nonzero boundary"
require_text "scripts/triparty-regression.sh" 'powershell_uninstaller_static_claw_history_cleanup' "Regression covers PowerShell historical Claw cleanup"
require_text "scripts/triparty-regression.sh" 'agentparty_write_state_blocks_non_triparty_true_ready' "Regression covers non-triparty true-triparty write guard"
require_text "scripts/triparty-regression.sh" 'agentparty_write_state_rejects_unknown_pack_schema' "Regression covers unknown pack-state schema write guard"
require_text "scripts/triparty-regression.sh" 'agentparty_install_blocks_target_os_spoof_execute' "Regression covers AgentParty target OS spoof blocking"
require_text "scripts/triparty-regression.sh" 'agentparty_release_check_quick_passes' "Regression covers AgentParty release-check quick gate"
require_text "scripts/triparty-regression.sh" 'agentparty_info_accepts_pack_flag' "Regression covers AgentParty info --pack alias"
require_text "scripts/triparty-regression.sh" 'agentparty_release_check_rejects_bad_web_command' "Regression rejects AgentParty release-check bad web command"
require_text "scripts/triparty-regression.sh" 'agentparty_package_creates_release_bundle' "Regression covers AgentParty release packaging"
require_text "scripts/triparty-regression.sh" 'global_uninstall_execute_is_idempotent' "Regression covers uninstall idempotency"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_blocks_forced_native_windows_shell' "Regression covers raw Bash installer native Windows blocking"
require_text "scripts/triparty-regression.sh" 'global_uninstall_blocks_forced_native_windows_shell' "Regression covers raw Bash uninstaller native Windows blocking"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_lock_blocks_concurrent_install' "Regression covers installer lifecycle lock"
require_text "scripts/triparty-regression.sh" 'global_uninstall_lock_blocks_concurrent_cleanup' "Regression covers uninstaller lifecycle lock"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_owner_metadata_static_contract' "Regression covers owner metadata write-back static contract"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_stale_reclaim_static_contract' "Regression covers stale reclaim fingerprint static contract"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_unverified_filesystem_static_contract' "Regression covers unverified filesystem static contract"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_unknown_filesystem_fails_closed' "Regression covers unknown filesystem fail-closed behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_empty_filesystem_fails_closed' "Regression covers empty filesystem fail-closed behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_bsd_df_candidate_fallback_installs' "Regression covers BSD df candidate fallback behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_darwin_df_candidate_fallback_installs' "Regression covers real Darwin df candidate fallback behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_nfs_df_candidate_fallback_fails_closed' "Regression covers NFS df candidate fail-closed behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_recovers_stale_lock' "Regression covers stale lock recovery"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_live_pid_lock_fails_safe' "Regression covers live PID fail-safe lock behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_foreign_host_lock_fails_safe' "Regression covers foreign-host fail-safe lock behavior"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_config_trailing_slash_lock_equivalence' "Regression covers config trailing slash lock equivalence"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_relative_parent_lock_equivalence' "Regression covers parent-segment lock equivalence"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_symlink_config_lock_equivalence' "Regression covers symlink config lock equivalence"
require_text "scripts/triparty-regression.sh" 'global_bootstrap_lock_root_trailing_slash_equivalence' "Regression covers lock-root trailing slash lock equivalence"
require_text "scripts/triparty-regression.sh" 'global_uninstall_cleans_legacy_claw_commands' "Regression covers historical Claw slash cleanup"
require_text "scripts/triparty-regression.sh" 'managed-install\.env' "Regression covers managed install manifest"
require_text "scripts/triparty-regression.sh" 'global_uninstall_resumes_after_interrupted_cleanup' "Regression covers interrupted cleanup resume"
require_text "scripts/triparty-regression.sh" 'global_uninstall_respects_absent_manifest_state' "Regression covers manifest absent state"
require_text "scripts/triparty-regression.sh" 'Skip modified Claude AgentParty Claw command file' "Regression covers modified Claw slash preservation"
require_text "scripts/triparty-regression.sh" 'global_uninstall_modified_user_file_preserved' "Regression covers modified user file preservation"
require_text "scripts/triparty-regression.sh" 'global_uninstall_partial_cleanup_verified' "Regression covers partial install cleanup"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_template_creates_bundle' "Regression covers Claw evidence template generation"
require_text "scripts/agentparty.py" 'def command_evidence_fill' "AgentParty CLI implements evidence-fill command"
require_text "scripts/agentparty.py" 'evidence-fill' "AgentParty CLI exposes evidence-fill"
require_text "scripts/agentparty.ps1" 'evidence-fill' "PowerShell wrapper exposes evidence-fill preparation"
require_text "README.md" 'agentparty evidence-fill' "README documents evidence-fill"
require_text "docs/framework/product-packs/claude-code-feishu-claw.md" 'evidence-fill' "Claw product-pack doc documents evidence-fill"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_rejects_invalid_link' "Regression rejects invalid Claw evidence links"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_rejects_non_feishu_link' "Regression rejects non-Feishu Claw evidence links"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_rejects_run_dir_mismatch' "Regression rejects Claw bundle run-dir mismatch"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_rejects_bundle_path_traversal' "Regression rejects Claw bundle artifact path traversal"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_rejects_tiny_bundle_files' "Regression rejects tiny Claw evidence files"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_evidence_bundle_marks_pack_ready' "Regression covers Claw bundle evidence ready state"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_guide_ready_next_steps' "Regression covers Claw guide ready state"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_direct_evidence_still_marks_pack_ready' "Regression preserves direct Claw evidence import"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_blocked_never_sets_true_triparty' "Regression covers Claw blocked non-triparty state"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_guide_blocked_next_steps' "Regression covers Claw guide blocked state"
require_text "scripts/triparty-regression.sh" 'agentparty_claw_guide_scoped_next_steps' "Regression covers Claw guide scoped state"

if [ "$FAILED" -eq 0 ]; then
  printf 'triparty lint passed\n'
  exit 0
fi

printf 'triparty lint failed\n' >&2
exit 1
